### ISSUE TITLE
Error with \setdiphthonglinecolor

### ISSUE THREAD

**Issue by tpellard** [flueterflam/tikz-vowel#1]
Using `\setdiphthonglinecolor` or related commands causes an error `! Undefined control sequence. \cs_tikzvowel_set_diphthong_options:nnnn ...nk:NT \g_tikzvowel_draw_tl`...I am using TeX Live 2020 with `pgf` 56512 (3.1.6a).

Here is a minimal example:

```LaTeX
\documentclass{article}
\usepackage{xcolor}
\usepackage{tikz-vowel}

\begin{document}
\begin{tikz-vowel}
\cardinalvowel{i}{1}
\cardinalvowel{u}{8}
\cardinalvowel{a}{4}
\cardinaldiphthong{a}{u}
\setdiphthonglinecolor{a}{u}{red}
\end{tikz-vowel}
\end{document}
```

**Comment by cweedall** [comment]
Thanks for bring this to my attention!

The issue is that latex3 has been changing regularly.  `l3regex` was deprecated and several of the argument specifiers have become deprecated over time.

There were some instances of `\tl_if_blank:NT`  and `\tl_if_empty:NT` that should have been `nT` variants.

That also led to some (now) undefined macro variants which could be generated via:

```
% Generate a xVTF variant for \regex_match:nVTF
\cs_generate_variant:Nn \regex_match:nVTF {xVTF}
%
% Generate a xnNF variant for \regex_replace_once:nnNF
\cs_generate_variant:Nn \regex_replace_once:nnNF {xnNF}
```

With these updates, I was able to generate your test document and also the documentation again.  Please check the updated version.
